### PR TITLE
Username limitations

### PR DESCRIPTION
**Pull request by LetsRaceBwoi**
Title explains all.

### CODE REVIEW

**Comment by ZackCDLVI** [comment]
I'd pull you in right away, if I could. But apparently I'm no longer wanted.

**Comment by RHY3756547** [comment]
It's not reasonable to pull issues without looking at the changes first anyways, so you'd ve wrong in doig that.

I'll be able to look over this later.

**Comment by RHY3756547** [comment]
Why disallow the name "username" exactly? Does this address an issue?

**Comment by ZackCDLVI** [comment]
Here we go again.

**Comment by LetsRaceBwoi** [comment]
https://github.com/Afr0Games/Project-Dollhouse/issues/116 - Yes, it does.

**Comment by ZackCDLVI** [comment]
You're welcome.

**Comment by RHY3756547** [comment]
Looks like the issue also mentions an "obscenity list", which would be much easier to extend to add more questionable words or phrases. You could check the username for all entries in this list, including the entry "username" to cover this base case you caught here. The list could probably just be stored as a cst, like the language string, or even just a plaintext list. If you're feeling adventurous, you could read the original game's censor.dat, (http://wiki.niotso.org/Censor.dat), and write a class to check a string for censored words out of it, which could be reused for the ingame chat!

I'm going to comment on the code you provided anyways, cause there are a few problems you should know about for any revisions.

**Comment by LetsRaceBwoi** [comment]
I'll get on "decoding" (is that the right word?) the censor.dat using code.  I'll implement it in & fix what you suggested.

**Comment by RHY3756547** [comment]
Parsing's a better word, but yes, that would be great.

**Comment by RHY3756547** [comment]
Afr0, this wasn't ready to merge... My comments haven't been addressed and I believe he's still working on a more generic system using censor.dat.

**Comment by LetsRaceBwoi** [comment]
Yes, it was not ready to merge and I'm not even sure username saving works (I never pushed the GlobalSettings files).  I was still working on censor.dat and that and was going to make a separate pull request later.

**Pull request merged**
