### PR TITLE
Custom content load from content folder, code expanded

### PR DESCRIPTION
**Pull request by francot514**
This also upate the custom content branch to be update with master

### CODE REVIEW

**Comment by LetsRaceBwoi** [comment]
You know, if you want me to merge this...

**Comment by Afr0** [comment]
Sorry :)

**Comment by Afr0** [comment]
Ugh, Github is telling me it can't be merged automatically :/

**Comment by LetsRaceBwoi** [comment]
I'll resolve the conflicts and merge it :smile:

**Comment by LetsRaceBwoi** [comment]
Actually, no I won't.  I will literally just mess it up :tongue:

**Comment by Afr0** [comment]
No, you won't. Please fix. :)

**Comment by LetsRaceBwoi** [comment]
Okay, I'll clone the branch and fix it.

**Comment by francot514** [comment]
You cna close this i made a mistake, cloning some master before it was updated to net version, maybe you should close this, ill do another if needed

**Comment by LetsRaceBwoi** [comment]
Okay.  Thanks for letting me know! :smile:

**Pull request closed without merging**
