### PR TITLE
Build network libs

### PR DESCRIPTION
**Pull request by ZackCDLVI**
These were disabled in the master branch too.

### CODE REVIEW

**Comment by LetsRaceBwoi** [comment]
Why the change from C# Express to VS 2010?

**Comment by ZackCDLVI** [comment]
I was on VS2010 Pro. It changes automatically.

**Comment by LetsRaceBwoi** [comment]
I vote merge; you can change the sln at any time with any sort of text reader, and if it still doesn't work it can easily be reverted.
:+1:

**Comment by ZackCDLVI** [comment]
VS Express and Pro solutions compatible as long as it doesn't contain any mixed project types.

**Comment by Afr0** [comment]
Wtf? I already metrged this change? O.o

**Comment by LetsRaceBwoi** [comment]
Doesn't look like it merged.  Want me to try and do it?

**Comment by ZackCDLVI** [comment]
@Afr0 
That was for buy-mode-initial.

**Comment by RHY3756547** [comment]
This change is now in since I merged buy-mode-initial. Closing.

**Pull request closed without merging**
