### PR TITLE
Change resolution via parameters

### PR DESCRIPTION
**Pull request by ZackCDLVI**
You got code from me. Thanks to @LetsRaceBwoi for helping me figure out this one last compiler error I faced.

### CODE REVIEW

**Comment by LetsRaceBwoi** [comment]
You could have made it dynamic (i.e. remove -r from the string and parse the two integers) but hey this is a good start.  Welcome to the code.  Permission to merge? @Afr0Games/owners

**Comment by Afr0** [comment]
Looks OK on a glance. I'm trusting you on this one, LetsRace. Merge!

**Comment by RHY3756547** [comment]
I can't make code comments because I'm blocked from your repository apparently? I'll just post them all here.

The old implementation that inferred the resolution from the string seemed like a more eloquent and flexible solution, why not fix that up?

```c#
        // 
        /// <summary>
        /// Converts and outputs a string array into a proper
        /// string using the Join method.
        /// </summary>
        /// <remarks>http://www.dotnetperls.com/convert-string-array-string</remarks>
        /// <param name="array"></param>
        static string ConvertStringArrayToStringJoin(string[] array)
        {
            //
            // Use string Join to concatenate the string elements.
            //
            string result = string.Join("", array);
            return result;
        }
```

Why did you implement a function for a one liner? Considering string.Join("", array); is pretty self explanatory anyways, this is a waste of space.

**Comment by ZackCDLVI** [comment]
I was tired. I'll get rid of it.

**Comment by RHY3756547** [comment]
Not the summary, the existence of the function in the first place.

**Comment by ZackCDLVI** [comment]
Oh. It was the only way I could make it work without getting errors.

**Comment by RHY3756547** [comment]
```c#
string userRes = string.Join("", args);
```
????

**Comment by ZackCDLVI** [comment]
Hey, it worked. xD Anyway, phasing that out for the old implementation. Will commit it in a sec.

**Comment by ZackCDLVI** [comment]
My implementation has been removed in favour of the older, more dynamic, one. Feel free to merge.

**Comment by LetsRaceBwoi** [comment]
Looks good from my perspective.

**Comment by Afr0** [comment]
Merged.

**Comment by ZackCDLVI** [comment]
Thank you.

**Pull request merged**
