### PR TITLE
Added EA Logo, build/buy music

### PR DESCRIPTION
**Pull request by LetsRaceBwoi**
Is this the wrong branch or is it OK to merge?

### CODE REVIEW

**Comment by Blayer98** [comment]
Keep in mind that build and buy mode music doesn't play. And the load loop starts when the EA Logo shows up

**Comment by LetsRaceBwoi** [comment]
The build/buy music plays fine for me.  And the load loop is meant to do that, since that's what happens in the original game :)

**Comment by RHY3756547** [comment]
TSO does not have build/buy music... Why did you merge this instantly?

**Comment by Afr0** [comment]
Heh, LetsRace looked over it. What's wrong with music? :D

**Comment by LetsRaceBwoi** [comment]
...?
The music is working absolutely fine here! The buildbot's build also works fine so I have no clue why yours isn't working...

**Comment by LetsRaceBwoi** [comment]
Ah, I get what you mean.  There was no build or buy music in TSO, and I didn't understand because you used the wrong tense ("does" as opposed to "did").  It depends on whether we want build/buy music or not though.

**Pull request merged**
