### PR TITLE
Prerequisites

### PR DESCRIPTION
**Pull request by ZackCDLVI**

### CODE REVIEW

**Comment by ZackCDLVI** [comment]
MonoGame is XNA. I think 3.4 finally includes all XNA APIs but I could be wrong. I'll include links to both.

**Comment by Afr0** [comment]
I will merge this, but Zack, I think if someone wanted to know about this (I.E they wanted to contribute to the project), they would ask us.
The fact that you took credit for Xezno coming back really says it all. Xezno didn't come back because you added information to the repository - he took time out and actually learned to code.
You should do the same thing.

**Comment by LetsRaceBwoi** [comment]
Him adding information did help me know what to add/change though, so he did _help_ me come back, sort of.  But yes, I did take a chunk of time out to learn to code in C# (which, once you've got your head around VB, Python & Java, is not difficult) and came back here after I wanted to get involved with a community again (and PD felt like home to me, so I returned).

**Comment by ZackCDLVI** [comment]
I wasn't trying to take credit. I was trying to show how my info helped him. All I've ever asked for in this entire train wreck was a thank you.

**Comment by ZackCDLVI** [comment]
I pointed out bugs or enhancements for developers to get at it to free up your work.

**Comment by Afr0** [comment]
"All I've ever asked for in this entire train wreck was a thank you."

Please. You stated our progress was slowed down, that we had a lack of transparency and lack of communication.

**Comment by ZackCDLVI** [comment]
> You stated our progress was slowed down, that we had a lack of transparency and lack of communication.

And I've been called retarded and useless by your best man. Do you really want start this all over again?

**Comment by Afr0** [comment]
If you commit more code, he won't do that, I promise ;)

Date: Mon, 22 Jun 2015 15:52:30 -0700

**Comment by ZackCDLVI** [comment]
> If you commit more code, he won't do that, I promise ;)

Yeah, no, that's not how you get me back. Unless you put him on a leash, no.

**Comment by LetsRaceBwoi** [comment]
Aidan, I have nothing against you, but he is right; Rhys was only being strict because you weren't meeting expectations.  I know you are trying your hardest to learn how to code, but please take some time off to learn more because your knowledge is not solid enough for you to contribute as of yet.  If you learn fast enough, you should be able to contribute again in a month or so.  And you really need to work on your anger issues, no offence...

**Comment by ZackCDLVI** [comment]
> Rhys was only being strict because you weren't meeting expectations.

All they want is coders. What I did was outside of that scope because I couldn't bare to witness to such an overall complex project have little guidance and prerequisites be only one willing to provide that knowledge. The fact we're now just finding out that the project works friendly on VS2010 further proves my point.

> And you really need to work on your anger issues, no offence...

None taken. Normally I can control it better.

**Comment by RHY3756547** [comment]
> And I've been called retarded and useless by your best man.
I would say that's pretty transparent. I don't know whats so hard about understanding that someone who cannot code or does not have any project management/life experience has no place in a complex software project. Someone who can't do either and can't even take criticism is even worse.

I also appear to have misunderstood how the block feature works, you should not be able to post here... I guess it works differently for organisations.

> The fact we're now just finding out that the project works friendly on VS2010 further proves my point.
We've known this for literally years. It should be pretty clear that with normal projects an "upgrade" to a later visual studio might cause incompatabilities that cause some
minor effort to be required. We will support VS2015 as soon as we can verify that monogame works with it.

**Comment by ZackCDLVI** [comment]
> I would say that's pretty transparent. I don't know whats so hard about understanding that someone who cannot code or does not have any project management/life experience has no place in a complex software project. Someone who can't do either and can't even take criticism is even worse.

So, you're idea of project management means no Getting Started, a lack of "up for grabs" tags, and no prerequisites, and transparency is calling people names and lowering their self-esteem.

> We've known this for literally years. It should be pretty clear that with normal projects an "upgrade" to a later visual studio might cause incompatabilities that cause some
minor effort to be required. We will support VS2015 as soon as we can verify that monogame works with it.

Project Dollhouse use to rely on VS2008 prior to the MonoGame switch and there was no, "btw, don't use anything higher then VS2010."

**Comment by ZackCDLVI** [comment]
Also, hello everyone getting these emails.

**Comment by ZackCDLVI** [comment]
As someone who use to admin forums, here's a better thought: "fuck it! unban him but give him read only access to the forums so we can chat this train wreck further in PMs." Because this right here is ridicules.

**Comment by LetsRaceBwoi** [comment]
>lowering their self-esteem
lowselfestem
(Sorry, I had to). 
On a serious note, VS2013 works with Monogame (with a bit of hacking) so VS2015 should too.  I'll download it and try it if you wish.  
>All they want is coders
Why do you think? They have a large enough workload with their team, of course they're going to need a bit of help to actually push the project forward faster.

**Comment by ZackCDLVI** [comment]
> Why do you think? They have a large enough workload with their team, of course they're going to need a bit of help to actually push the project forward faster.

Before you joined, Afr0 and Rhys have been working this project. That's not easy for a project with over hundreds or thousands of lines of code with an upcoming refactor. If you want more coders, you're gonna have to commit some non-code stuff.

**Comment by LetsRaceBwoi** [comment]
>you're gonna have to commit some non-code stuff

Yeah, I know.  But it would have been useful if you'd committed _some code stuff_.

**Comment by ZackCDLVI** [comment]
> Yeah, I know.

During this entire train wreck of a debate, you've been the most mature and aware one here. Thank you.

>  But it would have been useful if you'd committed some code stuff.

It's too late. Cut all my ties to this project today after Afr0's attempt to hook me in by doing *code stuff* which ruined any chance of an apology. My focus is now 3D modeling while tackling TS3, starting at the IO level. This discussion is just a wash, rinse, repeat of the forums. Nothing has changed.

**Comment by LetsRaceBwoi** [comment]
> while tackling TS3

1.  Can you even code yet?  AFAIK The Sims 3 is written in C#, C++.  That and you'll need knowledge of SimAntics.
2.  You're going to be sat there a while trying to decompress it - compression in 2009 was hotter than in 2002.
> you've been the most mature and aware one here
Can't tell if sarcasm.  If it isn't then thank you.  If it is, then please just move on.

**Comment by ZackCDLVI** [comment]
> Can you even code yet? AFAIK The Sims 3 is written in C#, C++. That and you'll need knowledge of SimAntics.

Not that big of a tackle. xD TS3 is still supported so there is no reason to take on the AI or pull a PD. All libraries are spread to their own independent repository, not crumpled into one.

> You're going to be sat there a while trying to decompress it - compression

Sounds like a fun challenge.

>  you've been the most mature and aware one here Can't tell if sarcasm. If it isn't then thank you. If it is, then please just move on.

I have. My only way of communication is through this one little pull request. I'm banned from the forums, remember?

**Comment by RHY3756547** [comment]
>So, you're idea of project management means no Getting Started, a lack of "up for grabs" tags, and no prerequisites, and transparency is calling people names and lowering their self-esteem for not doing things YOUR way? Lovely.

We've been distracted by other things that actually matter, considering that the project itself is not too friendly to new contributors due to the very dynamic nature of the system design in its current state, and the complicated build setup. The "attacks to your self esteem" were legitimate criticisms that you could have responded to instead of releasing what can only be described as the ultimate tard rage.

> Project Dollhouse use to rely on VS2008 prior to the MonoGame switch and there was no, "btw, use ONLY VS2010 and the Windows Phone SDK."

Yes there was, in a few places. People who didn't know how to build contacted me directly (francot, blayer) and everything worked fine, because we're not a big community and I only got one inquiry every few weeks. It's still not easy to build, even with some vague instructions written by someone who does not understand why the things mentioned are required, so I'll continue giving this much more helpful "in person" support.

> Also, hello everyone getting these emails.

Are you proud of yourself? It's pretty ironic that despite your attempts to gain contributors, you're actually scaring away and pissing them off by spamming their emails. I'm going to resolve this asap, until then please refrain from ragedumping into our issue tracker.

**Comment by LetsRaceBwoi** [comment]
>ultimate tard rage

You described it perfectly in three words.

>It's still not easy to build

C'mon, I managed to build it... That must mean it's at least a little bit easier...


Someone needs to lock this pull request.  It's getting too spammy :/

**Comment by ZackCDLVI** [comment]
> Are you proud of yourself? It's pretty ironic that despite your attempts to gain contributors, you're actually scaring away and pissing them off by spamming their emails. I'm going to resolve this asap, until then please refrain from ragedumping into our issue tracker.

No. I never asked for this to come up. That's why I said this earlier:

> Actually! As someone who use to admin forums, here's a better thought: "fuck it! unban him but give him read only access to the forums so we can chat this train wreck further in PMs." Because this right here is ridicules.

**Comment by RHY3756547** [comment]
You're not getting any access to the forums. I think it's pretty clear that the problem here is your attitude to being told there are better ways to do things, which consists of ignoring the advice completely, playing the victim and slamming your keyboard out of sheer rage for a good 5 seconds before removing what you typed and typing a "calm and collected" response that reeks of teenage moodswing tantrums that nobody who is not a high school teacher should ever be expected to deal with.

I am on holiday. This is my free time you are cutting into, and have been for the past 2 weeks. We are done. Do not post anything else on this issue tracker ever, if you want to contact me email me directly.

**Comment by LetsRaceBwoi** [comment]
Permission to block him from the repo? He's messing up the wiki.

**Comment by RHY3756547** [comment]
I've contacted Afr0 to block him via the organisation, which is the only way I think it'll work. If you have another soluton, give it a shot.

We can revert everything he does anyways. Nothing he does will have a lasting effect.

**Comment by LetsRaceBwoi** [comment]
I've "reverted" it in the best way I could.  You can view previous revisions of the "Home" page where he removed half of the text on it (the entire "Getting Started" section & "Bass.NET" section).

**Comment by LetsRaceBwoi** [comment]
Also, yes, blocking via the organisation appears to be the only way.  I thought if you were an owner you could block users from the repo but apparently not, sorry.

**Pull request merged**
